[project]
name = "asyncio-101"
version = "0.1.0"
description = "Learning asyncio from Python Concurrency with asyncio by Matthew Fowler"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp==3.8.1",
]
